FROM debian:buster

LABEL version="1.0" maintainer="raphael khelif <rkhelif@student.42.fr>"

RUN apt-get update
RUN apt-get upgrade
RUN apt-get install php-fpm -y
RUN apt-get install php-cli -y
RUN apt-get install php-mysql -y
RUN apt-get install php-json -y
RUN apt-get install php-mbstring -y
RUN apt-get install php-xml -y


